### PR TITLE
Added a number of missing methods and implementations

### PR DESCRIPTION
**Pull request by yangsu**

### CODE REVIEW

**Comment by yangsu** [comment]
Don't know why this keeps failing. The tests pass locally.

**Comment by chrisguttandin** [comment]
Hi @yangsu, many thanks for your pull request. I wonder why you installed `babel-plugin-transform-es2015-spread`. I couldn't find any new code which needs it. But I just had a brief look at your commits. However if you want to install it, you have to omit the `babel-plugin-` prefix in the babelify transform settings. Maybe that is causing the error on Travis.

**Comment by yangsu** [comment]
Oh oops. Meant to do that. Good catch!

As for the use of spread, [here you go](https://github.com/chrisguttandin/standardized-audio-context-mock/blob/master/src/registrar.js#L33).

**Comment by chrisguttandin** [comment]
Thanks for pointing me to the line where I used the spread operator. I usually don't transform already implemented features, I guess that's why the babel plugin was missing. Just out of curiosity, which browser do you have to support?

I have no idea why the tests still fail. I'm going to merge your pull request now and try to resolve the issue. Many thanks again.

**Comment by yangsu** [comment]
You are welcome. My use case is actually completely random. I wrote an [eslint config for p5.js](https://github.com/yangsu/eslint-config-p5js) and as a part of it I needed a script that could instantiate instances of p5 in jsdom and collect the global symbols it exports. p5.sound needed an implementation of the web audio api and I just needed a mock implementation to make sure it instantiates correctly. I tried a few other things before finding your repo, which is exactly what I needed. So I just filled in some the gaps and made it work. This is [what I'm doing with your repo](https://github.com/yangsu/eslint-config-p5js/blob/master/package.json#L17).

**Comment by chrisguttandin** [comment]
Thanks for sharing your project. I've got a last question. Do you need the constructors of the mocks for the `AudioBufferSourceNode`, `AudioNode`, `DynamicsCompressorNode` and `OscillatorNode` to be exported? I know that they are present in most (if not every) browser, but they can't and should not be instantiated and are not part of the standard. That's why I would like to remove them again if you don't desperately need them.

**Comment by yangsu** [comment]
yeah, i actually do need them because [p5.sound] augments the prototype of AudioContext, AudioNode, and AudioBufforeSourceNode. :(

Maybe we can have a different file that exports the nodes and only keep audio context in the top level module export.

**Comment by chrisguttandin** [comment]
Ah okay, I had one more look at the source of p5.sound and finally checked that they are using [Chris Wilson's monkeypatch](https://github.com/cwilso/AudioContext-MonkeyPatch). Finally it all makes sense. :-) Your pull request is available via [npm](https://www.npmjs.com/package/standardized-audio-context-mock) as version 0.2.0 now.

**Pull request merged**
